version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: con_ma_db
    environment:
      MYSQL_ROOT_PASSWORD: 'Password123$'
      MYSQL_DATABASE: madb
      MYSQL_USER: dba
      MYSQL_PASSWORD: 'Password123$'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Mount the init.sql file
    ports:
      - "3307:3306"
    networks:
      - app-network

  app:
    build: .
    container_name: con_ma_back
    environment:
      - HOST_NAME=my-mysql-container
    ports:
      - "5005:5005"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
